[package]
name = "gbam_tools"
version = "0.1.0"
authors = ["nickroz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
zstd = "0.5"
byteorder = "1.2.3"
flate2 = "1.0.1"
flume = "0.10.0"
num_cpus = "0.2"
bam_parallel = { git = "https://github.com/NickRoz1/bam_parallel" }
libc = "0.2.93"
serde_json = "1.0"
serde = {version = "1.0.125", features = ["derive"]}
bit-vec = "0.6.3"
crc32fast = "1.2.1"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[lib]
crate-type = ["rlib", "cdylib"]

[package.metadata.maturin]
requires-dist = ["pysam==0.16.0.1"]
