[package]
name = "gbam-binary"
version = "0.1.0"
authors = ["nickroz"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gbam-tools = { path = "../gbam-tools" }
byteorder = "1.2.3"
structopt = "0.3.21"
